version: "3"

services:
  api:
    container_name: api-auth-sys
    image: node:16.13.0
    build: backend
    command: bash -c "npm i && npm i -g knex && knex migrate:latest && knex seed:run && npm run dev"
    ports:
      - "8000:8000"
    working_dir: /src/backend
    volumes:
      - ./backend:/src/backend
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: auth_sys
      MYSQL_ROOT_PASSWORD: 123
    expose:
      - 3306
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
